
CREATE TABLE DEPARTMENT(DEPTNO NUMBER,NAME VARCHAR2(14)NOT NULL,
    PRIMARY KEY(DEPTNO),UNIQUE(NAME));
    
    

CREATE TABLE DLOCATION(DEPTNO NUMBER,LOCATION VARCHAR2(15)NOT NULL,
    PRIMARY KEY(DEPTNO,LOCATION),FOREIGN KEY(DEPTNO)
    REFERENCES DEPARTMENT(DEPTNO));
    
   
    
    CREATE TABLE EMPLOYEE(IDNUM NUMBER,FNAME VARCHAR2(15)NOT NULL,
        LNAME VARCHAR2(20) NOT NULL,SEX CHAR(1) NOT NULL,
        ADDRESS VARCHAR2(20)NOT NULL,SALARY NUMBER(7,2)NOT NULL,
        BONUS NUMBER(6,2),JOB VARCHAR2(20)NOT NULL,DEPTNO NUMBER NOT NULL,
        PRIMARY KEY(IDNUM),
        FOREIGN KEY(DEPTNO)REFERENCES DEPARTMENT(DEPTNO));
        
       
        CREATE TABLE DEPENDENT(IDNUM NUMBER,NAME VARCHAR2(15)NOT NULL,
        SEX CHAR(1) NOT NULL,
        BIRTHDATE DATE NOT NULL,RELATIONSHIP NUMBER(1)NOT NULL,
        PRIMARY KEY(IDNUM,NAME),
        FOREIGN KEY(IDNUM)REFERENCES EMPLOYEE(IDNUM));
        
 
                CREATE TABLE PROJECT(PROJNO NUMBER,NAME VARCHAR2(20)NOT NULL,
        LOCATION VARCHAR2(15)NOT NULL,DEPTNO NUMBER NOT NULL,
        PRIMARY KEY(PROJNO),UNIQUE(NAME));
        
        
        
        CREATE TABLE WORKSON(IDNUM NUMBER NOT NULL,PROJNO NUMBER NOT NULL,
        HOURS NUMBER(4),PRIMARY KEY(IDNUM,PROJNO),
        FOREIGN KEY(IDNUM)REFERENCES EMPLOYEE(IDNUM),
        FOREIGN KEY(PROJNO)REFERENCES PROJECT(PROJNO));

 